#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_dnsimple="0.0.1"
  jq -n --arg dnsimple "$ver_dnsimple" '{dnsimple: $dnsimple}'
}

version "$@"
